name: SQLibrary
version: ${version}
description: A facade similar to Vault that abstracts the coder from the JDBC and each database driver's implementation.
author: PatPeter, Yellowstrawberrys
main: lib.PatPeter.SQLibrary.SQLibrary